name: uno
favicon: null
layout_spectrum: 0.9353645793162286
typography_spectrum: 0.94595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050402'
    - '#302f2d'
    - '#bcbcbc'
    - '#595856'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
